---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2017 The Linux Foundation

version: 2

formats:
  - htmlzip

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
