---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 The Linux Foundation <abelur@linux.com>

name: call-github2gerrit-reusable-workflow

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      PR_NUMBER:
        description: "PR number to process; 0 processes all open"
        required: false
        default: "0"
        type: string
  pull_request_target:
    types: [opened, reopened, edited, synchronize, closed]
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

concurrency:
  # yamllint disable-line rule:line-length
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  call-in-g2g-workflow:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    # yamllint disable-line rule:line-length
    uses: lfreleng-actions/github2gerrit-action/.github/workflows/github2gerrit.yaml@f44ab263b27a93ea20af8a13647fdaaafa3da4eb  # v2.0.0
    with:
      GERRIT_KNOWN_HOSTS: ${{ vars.GERRIT_KNOWN_HOSTS }}
      GERRIT_SSH_USER_G2G: ${{ vars.GERRIT_SSH_USER_G2G }}
      GERRIT_SSH_USER_G2G_EMAIL: ${{ vars.GERRIT_SSH_USER_G2G_EMAIL }}
      ORGANIZATION: ${{ vars.ORGANIZATION }}
      PR_NUMBER: ${{ inputs.PR_NUMBER || '0' }}
    secrets:
      GERRIT_SSH_PRIVKEY_G2G: ${{ secrets.GERRIT_SSH_PRIVKEY_G2G }}
